# Generated by Django 6.0.3 on 2026-03-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="book",
            name="unique_book",
        ),
        migrations.AddConstraint(
            model_name="book",
            constraint=models.UniqueConstraint(
                fields=("author", "title", "cover"), name="unique_book"
            ),
        ),
    ]
