# Generated by Django 6.0.3 on 2026-03-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_remove_book_unique_book_book_unique_book"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="daily_fee",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
